name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Super-Linter
      uses: github/super-linter@v3.14.0

